client.out:082_send_outofbanddata.c
	gcc -o client.out 082_send_outofbanddata.c

server.out:083_recv_outofbanddata.c
	gcc -o server.out 083_recv_outofbanddata.c

clean:client.out server.out
	rm -f server.out 
	rm -f client.out
